# Generate frozen parity fixtures for the C++ migration.
#
# For each position it writes, using the Julia engine as the oracle:
#   - the canonical UHP game string (what the C++ parser will consume),
#   - perft counts for depths 1..DEPTH,
#   - the sorted list of legal root move strings (for move-gen parity).
#
# The C++ parity tests read these files and compare against them offline,
# so they never need a live Julia process.
#
# Usage (from repo root):
#   julia --project=. scripts/generate_cpp_fixtures.jl
#   julia --project=. scripts/generate_cpp_fixtures.jl --depth 4 --limit 25
#   julia --project=. scripts/generate_cpp_fixtures.jl --input starting_positions.txt \
#         --output intsect-cpp/intsect-tests/fixtures/perft_fixtures.txt --depth 4
#
# Notes:
#   - Lines in the input may be either a bare ';'-separated move sequence
#     (e.g. "wL;bL wL\;wM \wL;...") or a full game string starting with "Base".
#   - perft restores the board after each call, so depths are computed in sequence
#     on the same board.

using Intsect

const REPO_ROOT = normpath(joinpath(@__DIR__, ".."))

function parse_args(args)
    opts = Dict{String,String}(
        "input" => joinpath(REPO_ROOT, "starting_positions.txt"),
        "output" =>
            joinpath(REPO_ROOT, "intsect-cpp", "intsect-tests", "fixtures", "perft_fixtures.txt"),
        "depth" => "5",
        "limit" => "0",  # 0 means "all lines"
    )
    i = 1
    while i <= length(args)
        key = args[i]
        startswith(key, "--") || error("Unexpected argument: $key")
        name = key[3:end]
        haskey(opts, name) || error("Unknown option: $key")
        i + 1 <= length(args) || error("Missing value for $key")
        opts[name] = args[i + 1]
        i += 2
    end
    return opts
end

# Build a board from one input line, which is either a bare move sequence or a
# full "Base..." game string.
function board_from_line(line::AbstractString)
    parts = String.(strip.(split(strip(line), ';')))
    filter!(!isempty, parts)
    isempty(parts) && return nothing

    if startswith(parts[1], "Base")
        return from_game_string(join(parts, ';'))
    end

    board = handle_newgame_command(MLPGame)
    for mv in parts
        do_action(board, mv)
    end
    return board
end

# Sorted list of legal root move strings.
function root_moves(board)
    buf = Intsect.similar_move_buffer()
    indices = collect(Intsect.list_actions!(board, buf))
    moves = String[Intsect.move_to_str(board, i) for i in indices]
    sort!(moves)
    return moves
end

function main()
    opts = parse_args(ARGS)
    input = opts["input"]
    output = opts["output"]
    depth = parse(Int, opts["depth"])
    limit = parse(Int, opts["limit"])

    isfile(input) || error("Input file not found: $input")
    mkpath(dirname(output))

    lines = filter(!isempty, strip.(readlines(input)))
    if limit > 0
        lines = lines[1:min(limit, length(lines))]
    end

    open(output, "w") do io
        println(io, "# Intsect C++ parity fixtures")
        println(io, "# Generated by scripts/generate_cpp_fixtures.jl (Julia oracle)")
        println(io, "# Source: $(basename(input))  Depth: $depth  Positions: $(length(lines))")
        println(io, "# Block format:")
        println(io, "#   POSITION <n>")
        println(io, "#   GAMESTRING <canonical UHP game string>")
        println(io, "#   PERFT <d> <count>   (one line per depth 1..$depth)")
        println(io, "# Blocks are separated by a single blank line.")
        println(io)

        written = 0
        skipped = 0
        for (n, line) in enumerate(lines)
            board = nothing
            try
                board = board_from_line(line)
            catch err
                skipped += 1
                @warn "Skipping position $n: failed to build board" line exception = err
                continue
            end
            board === nothing && continue

            gs = Intsect.gamestring_to_string(GameString(board))
            counts = [perft(d, board) for d in 1:depth]

            println(io, "POSITION $n")
            println(io, "GAMESTRING $gs")
            for d in 1:depth
                println(io, "PERFT $d $(counts[d])")
            end
            println(io)

            written += 1
            println("[$n/$(length(lines))] depth-$depth perft=$(counts[depth]))")
        end

        return println("Wrote $written positions ($skipped skipped) to $output")
    end
end

main()
